on:
  push:
    branches:
      - master
    tags:
      - v1.*
  pull_request:
    branches:
      - master


name: Build&Test

jobs:
  test:
      strategy:
        matrix:
          go-version: [1.16.x]
          os: [ubuntu-latest, macos-latest, windows-latest]
      runs-on: ${{matrix.os}}
      steps:
        - name: Install Golang
          uses: actions/setup-go@v2
          with:
            go-version: ${{matrix.go-version}}
        - name: Checkout Code
          uses: actions/checkout@v2
        - name: Install
          run: go install ./...
        - name: Lint
          run:  make install-lint lint
        - name: Test
          run: make test
        - name: compile-all
          run: make compile-all
  release:
    needs: test
    if: startsWith(github.ref, 'refs/tags/v1')
    runs-on: ubuntu-latest
    steps:
      - name: Install Golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compile
        run: make install compile-all
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body:  Just look at the commit history if you need a changelog! 
          files: releases/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}