on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


name: Build&Test

jobs:
  test:
      strategy:
        matrix:
          go-version: 1.16.x
          os: [ubuntu-latest, macos-latest, windows-latest]
      runs-on: ${{matrix.os}}
      steps:
        - name: Install Golang
          uses: actions/setup-go@v2
          with:
            go-version: ${{matrix.go-version}}
        - name: Checkout Code
          uses: actions/checkout@v2
        - name: Lint
          run:  make install-lint lint
        - name: Test
          run: make test
        - name: Build ### Tests whether the build is succeeding 
          run: make build


  